spring:
  data:
    mongodb:
      database: allion_home_test
      host: localhost
      port: 27017
resilience4j.ratelimiter:
  instances:
    service1:
      limitForPeriod: 1
      limitRefreshPeriod: 120000
      timeoutDuration: 240000
resilience4j:
  circuitbreaker:
    instances:
      service1:
        registerHealthIndicator: true
        slidingWindowSize: 100

server:
  port: 9092
issue:
  tracking:
    url: http://localhost:8080/v1/getIssues
    cronExpression: "0 */5 * * * *"
